### PR TITLE
Revert new entities iterator

### PR DESCRIPTION
**Pull request by necessarily-equal**
See https://github.com/Unvanquished/Unvanquished/issues/2443

### CODE REVIEW

**Comment by DolceTriade** [comment]
Does this confirm fix the turrets? If so, LGTM.

**Comment by DolceTriade** [comment]
Actually this part is in the CBSE toolchain right? Does this part actually need to be reverted?

**Comment by necessarily-equal** [comment]
I found it needs to be reverted yes, and reverting only the latest commit doesn't work unfortunately. I confirm that this PR alongside https://github.com/Unvanquished/Unvanquished/pull/2444 fixes the turret on my end

**Comment by DolceTriade** [comment]
lgtm then

**Comment by slipher** [comment]
You only need to revert "Remove ForEntities"

**Comment by slipher** [comment]
I guess you might need to provide dummy callbacks in Unvanquished. Like copy and paste these
```
template<typename T> OnComponentCreate(T*) {}
template<typename T> OnComponentDestroy(T*) {}
```

**Comment by necessarily-equal** [comment]
I'll merge this now because I don't see a strong point for figuring a finer-tuned revert that would not save any used feature

**Pull request merged**
